# Generated by Django 3.2 on 2021-04-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_voucher',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='comprovante'),
        ),
    ]
